#!/usr/bin/env python3

import argparse
import json

from sentry_kafka_management.actions.topics import list_topics
from sentry_kafka_management.brokers import YamlKafkaConfig


def main():
    """Returns a list of topics"""
    parser = argparse.ArgumentParser(
        description="List Kafka topics using configuration file",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s -c config.yml
  %(prog)s -c config.yml -n my-cluster
  %(prog)s --config config.yml --cluster production
        """
    )

    parser.add_argument(
        '-c', '--config',
        required=True,
        help='Path to the YAML configuration file'
    )

    parser.add_argument(
        '-n', '--cluster',
        help='Name of the cluster to query (uses first available if not specified)'
    )

    args = parser.parse_args()

    config = YamlKafkaConfig(args.config)
    result = list_topics(config.get_clusters()[args.cluster])
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
