#!/usr/bin/env python3

from typing import Sequence
import json

from sentry_kafka_management.actions.topics import list_topics
from sentry_kafka_management.brokers import YamlKafkaConfig
from sentry_kafka_management.common import kafka_script_parser


def main(argv: Sequence[str] | None = None) -> int:
    """Returns a list of topics"""
    parser = kafka_script_parser(
        description="List Kafka topics using configuration file",
        epilog="""
Examples:
  %(prog)s -c config.yml -t topic.yml
  %(prog)s -c config.yml -t topic.yml -n my-cluster
  %(prog)s --cluster-config config.yml --topic-config topic.yml --cluster production
        """,
    )

    parser.add_argument(
        "-n",
        "--cluster",
        help="Name of the cluster to query (uses first available if not specified)",
    )

    args = parser.parse_args()

    config = YamlKafkaConfig(args.cluster_config, args.topic_config)
    result = list_topics(config.get_clusters()[args.cluster])
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    main()
