- name: local
  brokers:
    - kafka-kafka-1:9094
  security_protocol: PLAINTEXT
  sasl_mechanism: null
  sasl_username: null
  sasl_password: null
  topics:
  - name: test_topic
    partitions: 1
    replication_factor: 1
    placement:
      zone: zone1
    settings:
      retention.ms: 86400000
